### PR TITLE
Enabled nested fieldsets

### PR DESCRIPTION
**Pull request by vojtatranta**
Usages:
```
form_fieldsets = (
    ('Tvoje mama', {
        'fieldsets': (
            ('Title', {
               'fields': ['surname', 'name' , 'address']
            })
        ),
   }),
)

```

### CODE REVIEW

**Comment by LukasRychtecky** [comment]
I haven't even tested yet. But looks like good.

**Comment by matllubos** [comment]
I like it, please only fix fieldset[1] to value. 

You are using version 1.4 or 1.3?

**Comment by vojtatranta** [comment]
1.3

**Comment by matllubos** [comment]
so you must send pull request to the v1.3 branch

**Comment by vojtatranta** [comment]
Dont want it in 1.4? its mergable.

**Comment by matllubos** [comment]
Yes I want, I will merge and rebase changes inside 1.3 to 1.4 finally

**Pull request closed without merging**
